doc:
    resource: "@DocBundle/Controller/"
    type:     annotation
    prefix:   /

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
